### ISSUE TITLE
questa compile issue

### ISSUE THREAD

**Issue by jonopp2020** [rick-heig/zynq7-cosim#1]
I am trying to recreate your cosimulation example and ran into  a compile issue with Questa. I had to change the sccom command to use sccom -64 since i dont have the 32bit libraries but now i get this error from questa. Did you run into any issues with queseta compiling these libraries?
# sccom -reportprogress -work xil_defaultlib -g -I./libsystemctlm-soc/libremote-port/ -I./libsystemctlm-soc/ ./libsystemctlm-soc/libremote-port/remote-port-tlm.cc 
# Start time: 09:45:04 on Jun 09,2020
# 
# QuestaSim-64 sccom 2019.3 compiler 2019.07 Jul 24 2019
# 
# ./libsystemctlm-soc/libremote-port/remote-port-tlm.cc: In member function 'void remoteport_tlm::rp_pkt_main()':
# ./libsystemctlm-soc/libremote-port/remote-port-tlm.cc:313:18: error: 'errno' was not declared in this scope
#    if (r == -1 && errno == EINTR)
#                   ^
# ./libsystemctlm-soc/libremote-port/remote-port-tlm.cc:313:27: error: 'EINTR' was not declared in this scope
#    if (r == -1 && errno == EINTR)
#                            ^
# ** Error: (sccom-6142) Compilation failed.
# End time: 09:45:06 on Jun 09,2020, Elapsed time: 0:00:02
# Errors: 1, Warnings: 0

# Error in macro ./zynq7_compile_cosim.do line 21

# "sccom -64 -work xil_defaultlib -g -I./libsystemctlm-soc/libremote-port/ -I./libsystemctlm-soc/ ./libsystemctlm-soc/libremote-port/remote-port-tlm.cc"

**Comment by jonopp2020** [comment]
I also see additional compile errors with zynq_ps.h
I had to change the following...
 //auto tmp_irq = irq_f2p.read();
sc_bv<16> tmp_irq = irq_f2p.read();

but i continue to get this error in libsystemctlm_soc

sccom -64 -work xil_defaultlib -D__M_AXI_GP0_ENABLE__=1 -D__M_AXI_GP0_ADDR_WIDTH__=32 -D__M_AXI_GP0_DATA_WIDTH__=32 -D__M_AXI_GP0_ID_WIDTH__=12 -D__M_AXI_GP0_AXLEN_WIDTH__=4 -D__M_AXI_GP0_AXLOCK_WIDTH__=2 -g -I./libsystemctlm-soc/libremote-port/ -I./libsystemctlm-soc/ -I./libsystemctlm-soc/soc/xilinx/zynq/ -Isrc_sc -I. -I./libsystemctlm-soc/tlm-bridges/ src_sc/zynq7_ps.cc -verbose
sccom -work xil_defaultlib -D__M_AXI_GP0_ENABLE__=1 -D__M_AXI_GP0_ADDR_WIDTH__=32 -D__M_AXI_GP0_DATA_WIDTH__=32 -D__M_AXI_GP0_ID_WIDTH__=12 -D__M_AXI_GP0_AXLEN_WIDTH__=4 -D__M_AXI_GP0_AXLOCK_WIDTH__=2 -g -I./libsystemctlm-soc/libremote-port/ -I./libsystemctlm-soc/ -I./libsystemctlm-soc/soc/xilinx/zynq/ -Isrc_sc -I. -I./libsystemctlm-soc/tlm-bridges/ src_sc/zynq7_ps.cc -verbose 
Start time: 12:05:04 on Jun 09,2020

QuestaSim-64 sccom 2019.3 compiler 2019.07 Jul 24 2019

In file included from src_sc/zynq7_ps.h:49:0,
                 from src_sc/zynq7_ps.cc:26:
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h: In instantiation of 'void axi2tlm_bridge<ADDR_WIDTH, DATA_WIDTH, ID_WIDTH, AxLEN_WIDTH, AxLOCK_WIDTH, AWUSER_WIDTH, ARUSER_WIDTH, WUSER_WIDTH, RUSER_WIDTH, BUSER_WIDTH, ACE_MODE, CD_DATA_WIDTH>::Transaction::FillData(T1&, T2&) [with T1 = sc_core::sc_in<sc_dt::sc_bv<32> >; T2 = sc_core::sc_in<sc_dt::sc_bv<4> >; int ADDR_WIDTH = 32; int DATA_WIDTH = 32; int ID_WIDTH = 6; int AxLEN_WIDTH = 4; int AxLOCK_WIDTH = 2; int AWUSER_WIDTH = 2; int ARUSER_WIDTH = 2; int WUSER_WIDTH = 2; int RUSER_WIDTH = 2; int BUSER_WIDTH = 2; int ACE_MODE = 0; int CD_DATA_WIDTH = 32]':
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h:1222:4:   required from 'void axi2tlm_bridge<ADDR_WIDTH, DATA_WIDTH, ID_WIDTH, AxLEN_WIDTH, AxLOCK_WIDTH, AWUSER_WIDTH, ARUSER_WIDTH, WUSER_WIDTH, RUSER_WIDTH, BUSER_WIDTH, ACE_MODE, CD_DATA_WIDTH>::write_data_phase() [with int ADDR_WIDTH = 32; int DATA_WIDTH = 32; int ID_WIDTH = 6; int AxLEN_WIDTH = 4; int AxLOCK_WIDTH = 2; int AWUSER_WIDTH = 2; int ARUSER_WIDTH = 2; int WUSER_WIDTH = 2; int RUSER_WIDTH = 2; int BUSER_WIDTH = 2; int ACE_MODE = 0; int CD_DATA_WIDTH = 32]'
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h:243:3:   required from 'axi2tlm_bridge<ADDR_WIDTH, DATA_WIDTH, ID_WIDTH, AxLEN_WIDTH, AxLOCK_WIDTH, AWUSER_WIDTH, ARUSER_WIDTH, WUSER_WIDTH, RUSER_WIDTH, BUSER_WIDTH, ACE_MODE, CD_DATA_WIDTH>::axi2tlm_bridge(sc_core::sc_module_name, AXIVersion) [with int ADDR_WIDTH = 32; int DATA_WIDTH = 32; int ID_WIDTH = 6; int AxLEN_WIDTH = 4; int AxLOCK_WIDTH = 2; int AWUSER_WIDTH = 2; int ARUSER_WIDTH = 2; int WUSER_WIDTH = 2; int RUSER_WIDTH = 2; int BUSER_WIDTH = 2; int ACE_MODE = 0; int CD_DATA_WIDTH = 32]'
src_sc/zynq7_ps.h:1361:86:   required from here
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h:414:5: error: could not convert 'sc_dt::sc_proxy<X>::bit(int) const [with X = sc_dt::sc_bv_base](((int)i))' from 'sc_dt::sc_bitref_r<sc_dt::sc_bv_base>' to 'bool'
     if (wstrb.read().bit(i)) {
     ^
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h: In instantiation of 'void axi2tlm_bridge<ADDR_WIDTH, DATA_WIDTH, ID_WIDTH, AxLEN_WIDTH, AxLOCK_WIDTH, AWUSER_WIDTH, ARUSER_WIDTH, WUSER_WIDTH, RUSER_WIDTH, BUSER_WIDTH, ACE_MODE, CD_DATA_WIDTH>::Transaction::FillData(T1&, T2&) [with T1 = sc_core::sc_in<sc_dt::sc_bv<64> >; T2 = sc_core::sc_in<sc_dt::sc_bv<8> >; int ADDR_WIDTH = 32; int DATA_WIDTH = 64; int ID_WIDTH = 6; int AxLEN_WIDTH = 4; int AxLOCK_WIDTH = 2; int AWUSER_WIDTH = 2; int ARUSER_WIDTH = 2; int WUSER_WIDTH = 2; int RUSER_WIDTH = 2; int BUSER_WIDTH = 2; int ACE_MODE = 0; int CD_DATA_WIDTH = 64]':
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h:1222:4:   required from 'void axi2tlm_bridge<ADDR_WIDTH, DATA_WIDTH, ID_WIDTH, AxLEN_WIDTH, AxLOCK_WIDTH, AWUSER_WIDTH, ARUSER_WIDTH, WUSER_WIDTH, RUSER_WIDTH, BUSER_WIDTH, ACE_MODE, CD_DATA_WIDTH>::write_data_phase() [with int ADDR_WIDTH = 32; int DATA_WIDTH = 64; int ID_WIDTH = 6; int AxLEN_WIDTH = 4; int AxLOCK_WIDTH = 2; int AWUSER_WIDTH = 2; int ARUSER_WIDTH = 2; int WUSER_WIDTH = 2; int RUSER_WIDTH = 2; int BUSER_WIDTH = 2; int ACE_MODE = 0; int CD_DATA_WIDTH = 64]'
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h:243:3:   required from 'axi2tlm_bridge<ADDR_WIDTH, DATA_WIDTH, ID_WIDTH, AxLEN_WIDTH, AxLOCK_WIDTH, AWUSER_WIDTH, ARUSER_WIDTH, WUSER_WIDTH, RUSER_WIDTH, BUSER_WIDTH, ACE_MODE, CD_DATA_WIDTH>::axi2tlm_bridge(sc_core::sc_module_name, AXIVersion) [with int ADDR_WIDTH = 32; int DATA_WIDTH = 64; int ID_WIDTH = 6; int AxLEN_WIDTH = 4; int AxLOCK_WIDTH = 2; int AWUSER_WIDTH = 2; int ARUSER_WIDTH = 2; int WUSER_WIDTH = 2; int RUSER_WIDTH = 2; int BUSER_WIDTH = 2; int ACE_MODE = 0; int CD_DATA_WIDTH = 64]'
src_sc/zynq7_ps.h:1511:86:   required from here
./libsystemctlm-soc/tlm-bridges/axi2tlm-bridge.h:414:5: error: could not convert 'sc_dt::sc_proxy<X>::bit(int) const [with X = sc_dt::sc_bv_base](((int)i))' from 'sc_dt::sc_bitref_r<sc_dt::sc_bv_base>' to 'bool'
** Error: (sccom-6142) Compilation failed.
End time: 12:05:07 on Jun 09,2020, Elapsed time: 0:00:03
Errors: 1, Warnings: 0

**Comment by rick-heig** [comment]
Hello.
I did run the script with `sccom -64` there are no issues on my side. I am using Questa 2020.1_1 I don't know if this is version related.

For the first error you can add `#include <cerrno>` in ./libsystemctlm-soc/libremote-port/remote-port-tlm.cc

For the second error it seems for some reason it is not happy to convert `wstrb.read().bit(i)` to a boolean value. You could try to edit this manually to correct it (e.g, use == ... operation).

These errors occur in the code from https://github.com/Xilinx/libsystemctlm-soc
Maybe you could raise an issue there for this error specifically.

Maybe you could check `sccom -scversion` to be sure to have `SystemC version supported: 2.3.2`

Let us know if you can solve the issue and have it running, it would be nice to know if this works with Questa 2019.

Thank you for the feedback.

**Comment by jonopp2020** [comment]
Using Questa 2020.2 and adding -64 and --std=c++11  fixed the compile issues.

**Comment by rick-heig** [comment]
Thank you for the update.
It seems this requires Questa 2020 to function properly. (I tested older versions 10.5, 10.7 which did not support the current version of SystemC properly and went directly to 2020.1)

Glad you managed to get it to work.
And thank you for the comment on the required flags, this may help other users in the same situation.

Regards.
